### ISSUE TITLE
Support deploying to multiple org/spaces

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-spinnaker#77]
At the moment the spinnaker code base is using Boot 1.2.x, which doesn't support the use of SPRING_APPLICATION_JSON to specify collection values.  If spinnaker isn't upgraded to Boot 1.3, we need to provide support for a fixed set of org/space credentials via a basic number scheme, e.g. 

```
cf:
  accounts:
    - name: ${1.providers.cf.name}
      api: ${1.providers.cf.api}
      console: ${1.providers.cf.console}
      org: ${1.providers.cf.org}
      space: ${1.providers.cf.org}
      username: ${1.cf.account.name}
      password: ${1.cf.account.password}
      artifactUsername: ${1.cf.repo.username}
      artifactPassword: ${1.cf.repo.password}
    - name: ${2.providers.cf.name}
      api: ${2.providers.cf.api}
      console: ${2.providers.cf.console}
      org: ${2.providers.cf.org}
      space: ${2.providers.cf.org}
      username: ${2.cf.account.name}
      password: ${2.cf.account.password}
      artifactUsername: ${2.cf.repo.username}
      artifactPassword: ${2.cf.repo.password}
```

vs serialized json under SAJ
